### ISSUE TITLE
sync extension setting between browsers  setting not saved

### ISSUE THREAD

**Issue by RainJayTsai** [tarampampam/random-user-agent#12]
## Steps to reproduce:
 1.  close sync extension setting between browsers 
 2. restart chrome 
 3. the sync extension setting between browsers  are still open

## Expected behaviour:
Tell us what should happen
close the  sync extension setting between browsers 

## Actual behaviour:
Tell us what happens instead
the item not close it 
---------

### System information:
**Browser version**:  Google Chrome "57.0.2987.133"
```
For example: Google Chrome "52.0.2743.116 m", stable channel
```

**Extension version**:   2.1.1
```bash
For example: 2.0.1
```

**Console screenshot**:
> **Menu > Settings > More tools > Extensions > Developer mode (check) > Random User-Agent > Background Page**
![image](https://cloud.githubusercontent.com/assets/10095703/24806829/ab81c1a6-1be8-11e7-9d6e-c5c6ec1150e7.png)

![Console screenshot](https://cloud.githubusercontent.com/assets/7326800/17556647/98b7f4dc-5f2d-11e6-9eeb-ca2f3dd8e541.png)

**Comment by kentawr** [comment]
Periodically shuts spontaneously off at diverse sites.

Chrome 59.0.3071.86  Win7 64-bit

**Comment by tarampampam** [comment]
Dude, I cannot reproduce your error. This error is critical for you?

**Comment by RainJayTsai** [comment]
This cause browser to display a error render

**Comment by neroux** [comment]
What do you mean by "close"? That you cant disable that setting?

**Comment by RainJayTsai** [comment]
@neroux I can disable the setting. But after I close chrome with command+q on my macbook and restart chrome again, my setting switch to default setting. I expect that the extension will restore the last setting I had made after chrome restart.

**Comment by neroux** [comment]
So you mean you cant disable the sync?

**Comment by RainJayTsai** [comment]
yes

**Comment by neroux** [comment]
I seem to be able to confirm that.

I cant say for sure yet why it does it but I believe the issue is with how the settings are initialised and stored in the first place.

Chrome seems to offer [two storage areas for an extension](https://developer.chrome.com/extensions/storage), a strictly local one and one which it automatically synchronises with Google's servers.

The problem seems to be that the flag, indicating where the configuration is saved is part of that same configuration as well and so neither storage type ever gets a value not reflecting its own type ([load](https://github.com/tarampampam/random-user-agent/blob/master/extension/js/Settings.js#L81) and [save](https://github.com/tarampampam/random-user-agent/blob/master/extension/js/Settings.js#L105)). Considering that it [defaults to the synchable storage](https://github.com/tarampampam/random-user-agent/blob/master/extension/js/Settings.js#L33) it always loads its configuration from there and that configuration will always be set to "sync".

It should be fixable by splitting the sync flag from the main configuration and saving it always locally.

Did I miss something @tarampampam?

**Comment by dc9f7839** [comment]
For fix remenber the settings in chrome on windows choose your settings and close chrome and copy settings stocked in:
"%LocalAppData%\Slimjet\User Data\Default\Sync Extension Settings\einpaelgookohagofgnnkcfjbkkgepnpLocal Extension Settings\einpaelgookohagofgnnkcfjbkkgepnp" to 
"%LocalAppData%\Slimjet\User Data\Default\Sync Extension Settings\einpaelgookohagofgnnkcfjbkkgepnp"
Work for me, i just do it!!!!!!
Sorry for my english, i am not bilingual.

**Comment by neroux** [comment]
@RainJayTsai @kentawr @dc9f7839 There is a preliminary test version with a presumptive fix at https://github.com/tarampampam/random-user-agent/releases/download/sync/random_user_agent-2.2.3t1-an.fx.xpi

Could you give it a quick test and give me some feedback? Thanks.
