### ISSUE TITLE
More browsers to spoof

### ISSUE THREAD

**Issue by pogue** [tarampampam/random-user-agent#147]
The browser list is getting to be a little lackluster. There are plenty to choose from, but you can't use any of the Internet Explorer ones because they break the website. I would love to see Mozilla Firefox showing up on Redhat, Chrome on FreeBSD, Opera browser, Brave browser, etc.

Here are some browsers that could be spoofed on Windows, Linux and various other operating systems.

Thanks and keep up the good work!
pogue

**Comment by pogue** [comment]
> uc browser, duckgogo or yaani browser
I agree with my browsers being added, but I think they we should only be sticking with the [most popular browsers](https://www.google.com/search?q=most+popular+browsers) so as not to make the UI super long and filled with countless browsers. Also, Yaani browser is a mobile only browser and DuckDuckGo is a search engine, not a browser.

I would also like to see options for more operating systems, like maybe randomly give the ability to show you're running Windows, 7, 8, 10, or 11. Also, NetBSD, OpenBSD, FreeBSD would also be welcomed additions.

**Comment by augustusy** [comment]
Good idea，see this https://github.com/victor-savinov/user-agent/blob/master/data/user-agents.js

**Comment by pogue** [comment]
> Good idea，see this https://github.com/victor-savinov/user-agent/blob/master/data/user-agents.js and this https://github.com/tamimibrahim17/List-of-user-agents

I definitely wouldn't add XP/2000/98 as OSes for the browsers. The web page, if it will even parse properly, would have all sorts of warning boxes and I know most web servers block these browsers from accessing their servers.

Otherwise, looks good 👍

**Comment by tarampampam** [comment]
Because of the most popular browsers are:

![image](https://user-images.githubusercontent.com/7326800/195608098-a0001b79-4180-4a63-bfeb-4b94408d89e6.png)

They are included in this extension. Any less popular (like a UC browser, DuckDuckGo, and so on) can be used without limitations, but as custom user agents (or using remote user-agent lists), provided by the user.

From this point, I closing this issue, but if this request is still actual to someone - feel free to write here again or open a new issue. PRs are welcome :)
