### ISSUE TITLE
Optimize the blacklist setting UI

### ISSUE THREAD

**Issue by sharego** [tarampampam/random-user-agent#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

- Version: 3.5.0

- Description：

Black model setting in the same context with white model,  maybe confuses whats the following setting (Domain list and User define Rules) using for.

### Suggest a solution

Suggest the left menu name change to `websites setting`   from `blacklist setting `

Then  show  two radio button : 
 ○ enable blacklist：  all website enabled， except the following matched websites which configured
 ○ enable whitelist： only enabled the following matched websites which configured

Configure websites：

two tabs（Blacklist,  Whitelist）

Domain List:

User Define Rules:

 so can save blacklist configures and whitelist configures standalone.

### Additional context

Just my option, myabe you donot like.

**Comment by tarampampam** [comment]
Thanks for your issue! I will keep in mind your suggestion for future UI updates. But at the moment I don't have enough desire to greatly redesign the UI. Maybe you can do it? :)

**Comment by sharego** [comment]
Thanks, I can try,  not familiar with `vue`.

**Comment by robinpaulson** [comment]
> Then show two radio button :
> ○ enable blacklist： all website enabled， except the following matched websites which configured
> ○ enable whitelist： only enabled the following matched websites which configured

I think this is a good suggestion, at the moment the language feels a little convoluted. It took me at least three reads to understand it, I'm still not convinced I've got it right.

At the moment, it comes across as:
Blacklist or whitelist, enable or not?

**Comment by robinpaulson** [comment]
Even changing this line:
"Whitelist mode (blacklist mode - disabled, whitelist mode - enabled)"

to

"Enable use of whitelists instead of blacklists?",

or similar, would be an improvement

**Comment by robinpaulson** [comment]
I switched to a different addon, I'm not interested in fighting with convoluted language. Their settings are far easier to understand.

**Comment by DrStrange** [comment]
The "blacklist settings" ( I use quotes because this setting is for blacklisting and whitelisting as stated above) does not work in the manner as described in the options. With the setting ticked and showing a green box, I read this as the setting is enabled. Then the description to the left of this green box states that when it is enabled, the extension is in whitelist mode. Whitelist mode is decribed as "disabled everywhere except the specified domains & rules". However, if I go to a website that is not in the domains names list, I find that, when I left click the extension's icon for it's status, it shows the website is enabled on that domain (website), whereas the extension should have been disabled on that domain (website).

Also, if i disable "Whitelist mode (blacklist mode - disabled, whitelist mode - enabled)" (a cross inside an orange box), which should mean the extension is in blacklist mode, it actually turns the extension off altogether - general settings>enable switcher shows a cross with an orange box.

Am I interpreting this setting correctly?

Regardless of how it works, I do agree that renaming this feature would make it easier to understand. Maybe, rename the entire feature from "Blacklist Settings" to "Domain Access" and rename the line "Whitelist mode (blacklist mode - disabled, whitelist mode - enabled)" to "Blacklist mode - disabled, whitelist mode - enabled".

**Comment by tarampampam** [comment]
I will be very glad if someone makes a black/white list redesign (PRs are welcome), but at this point, I want to close this issue because of I have no plans to do it by myself, sorry for that.

**Comment by tarampampam** [comment]
The blacklist has been redesigned a bit (and one error was fixed), check the latest release, please 🥳
