### ISSUE TITLE
Allow quick change of the platform

### ISSUE THREAD

**Issue by ghost** [tarampampam/random-user-agent#394]
Hello!
I would like to be able to quickly switch between simulated systems.

For example:
- Android (random user agents for android systems)
- Linux (random user agents for Linux systems)
- Windows (random user agents for Windows systems)
- IOS (random user agents for IOS systems)
- Mac OS (random user agents for Mac OS systems)

This will be useful for testing any web sites and quickly switching between displaying pages without harming privacy.

**Comment by tarampampam** [comment]
Nice suggestion, thank you! As soon as I have some free time, I'll get to it. But I can't give an exact estimate of the time yet.

**Comment by tarampampam** [comment]
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿
