### ISSUE TITLE
Time in minutes is not saved in settings

### ISSUE THREAD

**Issue by acritum** [tarampampam/random-user-agent#40]
## Steps to reproduce:
 1. set time 1 minute
 2.
 3.

## Expected behaviour:
Tell us what should happen
should save 1 minute

## Actual behaviour:
Tell us what happens instead
returns to default 10 minutes
---------

### System information:
**Browser version**:
```
firefox 57
```

**Extension version**:
latest downloaded
```

*

**Comment by neroux** [comment]
Thanks, did you happen to change the value with the mouse and the spinner buttons? That would be a known issue at the moment, as [the input field currently still requires the value to be entered via the keyboard](https://github.com/tarampampam/random-user-agent/blob/master/extension/js/pages/options.js#L76). It should be fixed with the next version.

**Comment by neroux** [comment]
Should be fixed with 2.1.11

**Comment by acritum** [comment]
Thanks, keyboard value seems to work.
