### ISSUE TITLE
can't work well with ModHeader

### ISSUE THREAD

**Issue by passwa11** [tarampampam/random-user-agent#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when [ModHeader](https://modheader.com/docs/modheader)(set some X-Forwarded-For no ua) work with random-user-agent together , the ua can't be changed by random-user-agent . I'm not sure which extension is causing the problem or the chrome api?

### Steps to reproduce

install two ext and open the github

### Browser

Chrome

### Extension version

latest

**Comment by tarampampam** [comment]
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿
