### ISSUE TITLE
CSP error on github.com

### ISSUE THREAD

**Issue by bodograumann** [tarampampam/random-user-agent#59]
When opening github.com with random user agent enabled, there is Content Security Policy error
and a lot of functionality on the page is disrupted. E.g. loading the current commit, switching between HTTPS and SSH cloning or posting comments.

![screenshot_20180519-095844](https://user-images.githubusercontent.com/1223583/40266441-6d35da2e-5b4b-11e8-9fd3-e7e1c6e31918.png)

The error occurs even when all other extensions are disabled.

System
---------
Name: 	Firefox
Version: 	60.0.1
Build-ID: 	20180516032328
Update-Kanal: 	release
User-Agent: 	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Betriebssystem: 	Linux 4.12.12-gentoo

**Comment by neroux** [comment]
Thanks for the report, that issue might be related to #24, or even a continuation of it.

I can reproduce it, however it would appear the useragent override is still working (evaluating `navigator.userAgent` still returns the desired agent string).

As for the site breaking, I couldnt reproduce it so far, but if it happens I would attribute it rather to browser sniffing than to that error message.

**Comment by neroux** [comment]
Judging from a preliminary analysis it seems complicated :)

First, the script really does seem to fail. The fact that the override still seems to take place is owed to something else. Interestingly enough, Chrome does not seem to interpret the CSP in that way and does execute the script, in Firefox however the only possible solution I could find so far is to include the script not _inline_ but via the `src` attribute, loading it via `chrome.runtime.getURL` (which however does not seem to work on Chrome ;) ).

Second, aforementioned reason why the override still works seems to be because the extension does not only override the JavaScript value but also the HTTP header. For some reason, it seems doing that automatically also changes the JavaScript value, this only on Firefox however. As the extension always overrides the HTTP header it would appear the toggle to enable and disable the JavaScript override does not have any effect on Firefox.

**Comment by neroux** [comment]
> As for the site breaking, I couldnt reproduce it so far, but if it happens I would attribute it rather to browser sniffing than to that error message.

@bodograumann Could you please comment on this bit and try to reproduce it with Firefox-only settings? Thanks.

**Comment by neroux** [comment]
No feedback, closing.

**Comment by bodograumann** [comment]
Your idea is correct. Github breaks, because the user-agent was set to chrome and apparently github then uses features, which are not available in firefox.
When only allowing firefox user-agent strings with random-user-agent, github works again.
Unfortunately this can not be selected just for a specific site and I’m not sure how effective the extension is, if I would only allow firefox-based user-agents. So deactivating it on github still seems the best option.

**Comment by neroux** [comment]
Thanks for the feedback. There is little the extension can do about the Github related issue, however the CSP related error on Firefox should be still fixed at some point. `getURL` might be a fix for this, though as it seems so far the entire injected JavaScript might be obsolete on Firefox for the reason mentioned earlier.

> Unfortunately this can not be selected just for a specific site and I’m not sure how effective the extension is, if I would only allow firefox-based user-agents. So deactivating it on github still seems the best option.

#45 is requesting that feature.

**Comment by neroux** [comment]
Reopening as confirmed issue.

I split the CSP error from the Firefox issue and opened a separate issue for the latter (#60). Once #60 is fixed the issue here will be automatically fixed as well, as there wont be a script injection anymore.

**Comment by neroux** [comment]
Should be fixed with the fix of #60.
