### ISSUE TITLE
minimum time in seconds for random user agent changes

### ISSUE THREAD

**Issue by DaddyMadu** [tarampampam/random-user-agent#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

good day!

i see no info in change log regarding changing Automatically change the User-Agent after specified period of time

in Version 3.19.0 the minimum time in seconds i can set was 1 second and i was using that alot 

in Version 4.0.0 the minimum becomes 30 sec, i'm forced to use the old version with auto update is disabled.

i really like the addon and no other firefox addon is offering the same options, and i'm worried of using outdated plugin for so long

can you please let us set the the minimum amount manually instead of forcing us to do so via presets 

thank you so much, 

wish you a great day as always!

### Suggest a solution

allow us set the the minimum amount manually instead of forcing us to do so via presets 
![image](https://github.com/tarampampam/random-user-agent/assets/9450141/fef7c7c7-94fa-417f-8896-80ff9f22e790)

**Comment by tarampampam** [comment]
Unfortunately, to migrate to MV3, I needed to use the Timers API instead of the previously used functions that could run at intervals limited only by our imagination. Here is the additional description of why the minimum timer interval is limited to 30 seconds:

https://github.com/tarampampam/random-user-agent/blob/1ee9939b7937055b2df9e874c5510a6b07f00187/src/entrypoints/background/timer/timer.ts#L2-L8
