### ISSUE TITLE
Addon breaks XML viewer in Firefox

### ISSUE THREAD

**Issue by Xorok** [tarampampam/random-user-agent#98]
The addon breaks the integrated XML viewer in Firefox, at least on the websites I tested. Disabling the addon for the domain fixes the problem. How about a "disable addon on all .xml documents" option?

https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml
https://www.w3schools.com/xml/note.xml

**Comment by neroux** [comment]
Thanks Adrian. This issue seems to occur only on Firefox and it would appear the reason is the script injection to override the `navigator` object.

Considering that override is not really necessary on Firefox (see #60 please) it should be sufficient if you disable "Protect against detection by Javascript (experimental)". That should be a viable workaround until #60 is addressed.

**Comment by Xorok** [comment]
Ok, works for me :)

**Comment by neroux** [comment]
Should be fixed with the fix of #60.
